name: ovpn3-connect-action
description: 
  Setup vpn using a self-contained .ovpn file
inputs:
  ovpn-config:
    description: Complete self-contained .ovpn file
    required: true
  vpn-user:
    description: Username for the VPN
    required: false
  vpn-pass:
    description: Password for the VPN
    required: false
runs:
  using: composite
  steps:
    - name: Write VPN Files
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ovpn-config }}" > .github/vpn.ovpn
        ls -al .github/vpn.ovpn
    - name: Install openvpn3
      shell: bash
      run: |
        sudo apt install apt-transport-https
        sudo mkdir -p /etc/apt/keyrings && curl -fsSL https://packages.openvpn.net/packages-repo.gpg | sudo tee /etc/apt/keyrings/openvpn.asc
        DISTRO=`lsb_release -c -s`; echo "deb [signed-by=/etc/apt/keyrings/openvpn.asc] https://packages.openvpn.net/openvpn3/debian $DISTRO main" | sudo tee /etc/apt/sources.list.d/openvpn-packages.list
        sudo apt update
        sudo apt install openvpn3
    - name: VPN Connect
      shell: bash
      run: |
        echo "${{ inputs.vpn-user }}" >> .github/vpn-user.txt
        echo "${{ inputs.vpn-pass }}" >> .github/vpn-pass.txt
        ls -al .github
        { echo "${{ inputs.vpn-user }}" ; echo "${{ inputs.vpn-pass }}" ; } | openvpn3 session-start --config .github/vpn.ovpn
